version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
      # - .env.local
    depends_on:
      # - qdrantc
      - db

#   qdrant:
#     image: qdrant/qdrant
#     ports:
#       - "6333:6333"
#     volumes:
#       - qdrant_data:/qdrant/storage

  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5555:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
  
  scrape:
    build:
      context: ./scrape
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=admin
      - PGDATABASE=postgis

volumes:
#   qdrant_data:
  db_data: