version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
      # - .env.local
    depends_on:
      - qdrant
      - db

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5555:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  db_data: